--- !ZMirror


# enable logging of the environment variables for all reltest-systemnt events
log_env: yes


content:










  # a zpool cannot be taken offline, once all of its backing blockdevs have disappeared (reboot manually)
  - !ZPool 
    name: zmirror-sysfs







  # partitions are considered top-level in this configuration. 
  # we could implement disks and below partitions, but since both disks and partitions cannot be taken offline (only their containers can if that is the case)
  # we don't need to implement this
  - !Partition

    # partition names for zmirror must be unique
    name: zmirror-sysfs-a
    
    content:
      - !DMCrypt

        # name of dm-crypt
        name: zmirror-sysfs-a
        
        key-file: ./test/zmirror-key

        on_parent_online:
          - online

        on_children_offline: 
          - offline

        content:
          # the zfs blockdev inside the partition
          - !ZFSBackingBlockDevice
            # name for the zfs pool
            pool: zmirror-sysfs
          
            # the name of the zfs-backing blockdev as it appears in `zpool status`
            dev: zmirror-sysfs-a

            on_parent_online: 
              - import-pool
              - online

            scrub_interval: 3 weeks



  - !Partition

    # partition names used by zmirror must be unique
    name: zmirror-sysfs-b

    
    content:
      - !DMCrypt

        # name of dm-crypt
        name: zmirror-sysfs-b
        
        key-file: ./test/zmirror-key

        on_children_offline: 
          - offline

        on_parent_online:
          - online

        content:
          - !ZFSBackingBlockDevice
          
            dev: zmirror-sysfs-b
            pool: zmirror-sysfs

            on_parent_online: 
              - online

            scrub_interval: 1 week












  - !ZPool
    name: zmirror-big







  - !Partition

    # partition names for zmirror must be unique
    name: zmirror-big-a

    content:
      - !DMCrypt

        # name of dm-crypt
        name: zmirror-big-a
        
        key-file: ./test/zmirror-key

        on_children_offline: 
          - offline
        
        on_parent_online:
          - online

        content:
          # the zfs blockdev inside the partition
          - !ZFSBackingBlockDevice
          
            # the name of the zfs-backing blockdev
            dev: zmirror-big-a

            # name for the zfs pool
            pool: zmirror-big
          
            on_parent_online:
              - import-pool
              - online

            scrub_interval: 3 weeks






  - !Partition

    # partition names used by zmirror must be unique
    name: zmirror-big-b

    
    content:
      - !DMCrypt

        # name of dm-crypt
        name: zmirror-big-b
        
        key-file: ./test/zmirror-key

        on_children_offline: 
          - offline

        content:

          - !ZFSBackingBlockDevice
          
            dev: zmirror-big-b

            pool: zmirror-big
          

            on_parent_online:
              - online

            scrub_interval: 3 week






  - !ZPool
    name: zmirror-bak-a

    on_children_offline: 
      - offline

    content:
      
      - !ZFSVolume
        name: sysfs

        on_children_offline: 
          - snapshot
          - offline
        
        content:
          # it is important that all physical volumes are configured
          - !ZFSBackingBlockDevice
            pool: zmirror-sysfs
            dev: zvol/zmirror-bak-a/sysfs

            on_scrubbed: 
              - offline

            on_resilvered: 
              - offline

            on_parent_online:
              - online
      
      - !ZFSVolume
        name: big
        
        on_children_offline: 
          - snapshot
          - offline
        
        content:
          
          - !ZFSBackingBlockDevice
            
            dev: zvol/zmirror-bak-a/big
            pool: zmirror-big

            on_parent_online:
              - online

            on_scrubbed: 
              - offline

            on_resilvered: 
              - offline






  - !Partition
    name: zmirror-bak-a

    content:
      - !DMCrypt
        name: zmirror-bak-a
        key-file: ./test/zmirror-key
        
        on_parent_online:
          - online
        
        on_children_offline: 
          - offline

        content: 
          # zfs blockdev inside the partition
          - !ZFSBackingBlockDevice
            
            dev: zmirror-bak-a
            
            # name of the zfs pool
            pool: zmirror-bak-a
          
            on_parent_online:
              - online

            scrub-interval: 3 weeks











  # once a zpool is being exported, we must generate a "virtual event", because now all backing blockdevs are considered to be offline (so their parent's handle_child_offline method must be called)
  - !ZPool
    name: zmirror-bak-b

    on_children_offline: 
      - offline

    content:
      
      - !ZFSVolume
        name: sysfs
        on_children_offline: 
          - snapshot
          - offline
        content:

          - !ZFSBackingBlockDevice
            dev: zvol/zmirror-bak-b/sysfs
            pool: zmirror-sysfs
            
            on_parent_online: 
              - online
          
            on_scrubbed: 
              - offline

            on_resilvered: 
              - offline
      
      - !ZFSVolume
        name: big
        on_children_offline: 
          - snapshot
          - offline
        content:
          # it is important that all physical volumes are configured
          - !ZFSBackingBlockDevice
            # pvdisplay
            dev: zvol/zmirror-bak-b/big
            pool: zmirror-big

            on_parent_online: 
              - online
          
            on_scrubbed: 
              - offline

            on_resilvered: 
              - offline








  - !Partition
    name: zmirror-bak-b

    content:
      - !DMCrypt
        name: zmirror-bak-b
        key-file: ./test/zmirror-key

        on_parent_online:
          - online

        on_children_offline: 
          - offline

        content: 

          - !ZFSBackingBlockDevice

            dev: zmirror-bak-b

            pool: zmirror-bak-b
          
            on_parent_online:
              - online







