--- !ZMirror


# enable logging of the environment variables for all relevant events
log_env: yes


# application state:
# /var/lib/zmirror/cache.st
# finished scrub & active devices



# zmirror trigger

# zmirror scrub: starts all scrubs that are pending for which the devices are connected
#     

# zmirror status:
# eva-a-main @Dm-Crypt
#
#     #disconnected|online
#
#     eva/eva-a-main @ZFS_Blockdev
#
#         #disconnected | present-but-offline | online
#
#         operation
#            
#            # start time
#            resilvering: 2024-12-12'18:45:12
# 
#            # start time
#            scrubbing: 2024-12-12'18:54:34
#            
#         # finish time
#         last resilvered: 2025-12-12'14:48:41 | unknown
#         last scrubbed: 2021-12-12'14:58:14 | unknown
#
#         scrub: pending | overdue
#            since: 2021-12-12


content:
    - !Partition

        # either: name for matching partition
        name: eva-a-main

        # or: uuid for matching partition
        # uuid: ...

        # or: udev environment variables for matching partition
        # udev: 
        #     FS_UUID: ...
        
        content:
            - !DM_Crypt

                # name of dm-crypt
                name: eva-a-main
                
                key-file: /dev/disk/by-partlabel/eva-key

                content:
                    # the zfs blockdev inside the partition
                    - !ZFS_Blockdev
                        # name for the zfs pool
                        pool: eva
                    
                        # the name of the zfs blockdev
                        dev: eva-a-main
                    
                        # what to do when a scrub finishes
                        on_scrubbed:
                            - offline
                            
                        on_offline:
                            - offline-parent

                        scrub_interval: 3 weeks

                        # what to do when a resilver finishes
                        on_resilvered: schedule-scrub


    - !Partition

        # either: name for matching partition
        name: eva-b-main

        # or: uuid for matching partition
        # uuid: ...

        # or: udev environment variables for matching partition
        # udev: 
        #     FS_UUID: ...
        
        content:
            - !DM_Crypt

                # name of dm-crypt
                name: eva-b-main
                
                key-file: /dev/disk/by-partlabel/eva-key

                content:
                    # the zfs blockdev inside the partition
                    - !ZFS_Blockdev
                        # name for the zfs pool
                        pool: eva
                    
                        # the name of the zfs blockdev
                        dev: eva-b-main
                    
                        # what to do when a scrub finishes
                        on_scrubbed: offline-parent
                        # or just offline

                        # what to do when a resilver finishes
                        on_resilvered: scrub

                        scrub_interval: 1 week

            
    - !Partition
        name: bak-gamma
        key-file: /dev/disk/by-partlabel/eva-key

        on_offline: offline-parent

        content:
            - !LVM_Physical_Volume
                
                lvm_volume_group: vg-eva-bak-gamma

                on_offline: offline-parent


    - !LVM_Volume_Group
        name: vg-eva-bak-gamma
        on_offline: offline-parent

        content:
            - !LVM_Logical_Volume
                name: lv-eva-bak-gamma

                on_offline: offline-parent
                content:
                    - !ZFS_Blockdev
                        pool: eva
                        dev: vg-eva-bak-gamma/lv-eva-bak-gamma

                        on_scrubbed: offline-parent
                        
                        # what to do when a resilver finishes
                        on_resilvered: scrub
                    

            - !LVM_Logical_Volume
                name: lv-big-bak-gamma
                on_offline: offline-parent
                content: 
                    - !ZFS_Blockdev
                        pool: big
                        dev: vg-eva-bak-gamma/lv-big-gamma

                        on_scrubbed: offline-parent
                        
                        # what to do when a resilver finishes
                        on_resilvered: scrub



    # bak-delta
    - !Disk
        serial: TOSHIBA_MG09ACA18TE_71L0A33JFQDH

        content:
            - !DM_Crypt
                name: bak-delta
                key-file: /dev/disk/by-partlabel/eva-key

                content: 
                    # zfs blockdev inside the partition
                    - !ZFS_Blockdev
                        # name for the zfs pool
                        pool: bak-delta
                    
                        # the name of the zfs blockdev
                        dev: bak-delta
                    
                        # or just offline
                        on_scrubbed: offline-parent

                        scrub-interval: 3 weeks


    - !ZPool 
        name: eva
        on_offline: offline-parents





    - !ZPool
        name: bak-delta

        # zfs: bak-delta

        # offline-parents = take offline the blockdevs backing the zpool, and (if configured) take of their parents as well
        on_offline: offline-parents

        content:
            
            - !Volume
                name: backups
                on_offline: snapshot | offline-parent
                content:
                    - !LVM_Physical_Volume
                        volume-group: vg-bak-delta
        

    - !LVM_Volume_Group
        name: vg-bak-delta
        on_offline: offline-parent
        
        content:
            - !LVM_Logical_Volume 
                name: eva

                on_offline: offline-parent
                content:
                    - !ZFS_Blockdev
                        pool: eva
                        dev: vg-bak-delta/eva

                        on_scrubbed: offline-parent
                        
                        # what to do when a resilver finishes
                        on_resilvered: scrub
                    

            - !LVM_Logical_Volume 
                name: big
                on_offline: offline-parent
                content: 
                    - !ZFS_Blockdev
                        pool: big
                        dev: vg-bak-delta/big

                        on_scrubbed: offline-parent
                        
                        # what to do when a resilver finishes
                        on_resilvered: scrub


