--- !ZMirror


# enable logging of the environment variables for all reltest-systemnt events
log_env: yes


content:









  # a zpool cannot be taken offline, once all of its backing blockdevs have disappeared (reboot manually)
  - !ZPool 
    name: test-sysfs








  # partitions are considered top-level in this configuration. 
  # we could implement disks and below partitions, but since both disks and partitions cannot be taken offline (only their containers can if that is the case)
  # we don't need to implement this
  - !Partition

    # partition names for zmirror must be unique
    name: test-sysfs-a

    
    content:
      - !DMCrypt

        # name of dm-crypt
        name: test-sysfs-a
        
        key-file: /dev/disk/by-partlabel/eva-key

        on_children_offline: offline

        content:
          # the zfs blockdev inside the partition
          - !ZFSBlockdev
            # name for the zfs pool
            pool: test-sysfs
          
            # the name of the zfs blockdev
            dev: test-sysfs-a-main
          
            # what to do when a scrub finishes
            on_scrubbed: offline
            # or just offline

            scrub_interval: 3 weeks

            # what to do when a resilver finishes
            on_resilvered: scrub


  - !Partition

    # partition names used by zmirror must be unique
    name: test-sysfs-b-main

    
    content:
      - !DMCrypt

        # name of dm-crypt
        name: test-sysfs-b-main
        
        key-file: /dev/disk/by-partlabel/eva-key

        on_children_offline: offline

        content:
          # the zfs blockdev inside the partition
          - !ZFSBlockdev
            # name for the zfs pool
            pool: test-sysfs
          
            # the name of the zfs blockdev
            dev: test-sysfs-b-main
          
            # what to do when a scrub finishes
            on_scrubbed: offline
            # or just offline

            # what to do when a resilver finishes
            on_resilvered: scrub

            scrub_interval: 1 week












  - !ZPool
    name: test-big







  - !Partition

    # partition names for zmirror must be unique
    name: test-big-a

    content:
      - !DMCrypt

        # name of dm-crypt
        name: test-big-a
        
        key-file: /dev/disk/by-partlabel/eva-key

        on_children_offline: offline

        content:
          # the zfs blockdev inside the partition
          - !ZFSBlockdev

            # name for the zfs pool
            pool: test-big-a
          
            # the name of the zfs blockdev
            dev: test-big-a
          
            # what to do when a scrub finishes
            on_scrubbed: offline

            scrub_interval: 3 weeks

            # what to do when a resilver finishes
            on_resilvered: offline-until-scrub





  - !Partition

    # partition names used by zmirror must be unique
    name: test-big-b

    
    content:
      - !DMCrypt

        # name of dm-crypt
        name: test-big-b
        
        key-file: /dev/disk/by-partlabel/eva-key

        on_children_offline: offline

        content:
          # the zfs blockdev inside the partition
          - !ZFSBlockdev
            # name for the zfs pool
            pool: test-big
          
            # the name of the zfs blockdev
            dev: test-big-b
          
            # what to do when a scrub finishes
            on_scrubbed: offline
            # or just offline

            # what to do when a resilver finishes
            on_resilvered: scrub

            scrub_interval: 1 week






  - !Partition
    name: test-bak-gamma

    content:
      - !DMCrypt

        # name of dm-crypt
        name: test-bak-gamma
        
        key-file: /dev/disk/by-partlabel/eva-key

        content: 
          - !LVMPhysicalVolume
            
            # pvdisplay
            pv_uuid: Zjo2cC-STQR-o5Eq-mdJs-HID0-wa9i-yudslS
            lvm_volume_group: vg-test-bak-gamma


            # when the group goes offline, then the volume is considered (virtually) offline!
            # this is the n-to-1 relation
            # 
            #
            # call on_group_offline() --> parent.on_child_offline()








  - !LVMVolumeGroup
    name: vg-test-bak-delta
    on_offline_children: offline
    
    content:
      - !LVMLogicalVolume 
        name: sysfs

        on_offline_children: offline
        content:
          - !ZFSBlockdev
            pool: sysfs
            dev: vg-test-bak-delta/sysfs

            on_scrubbed: offline
                
            # what to do when a resilver finishes
            on_resilvered: offline-for-scrub
              

      - !LVMLogicalVolume 
        name: big
        on_offline_children: offline
        content: 
          - !ZFSBlockdev
            pool: big
            dev: vg-bak-delta/big

            on_scrubbed: offline
            
            # what to do when a resilver finishes
            on_resilvered: offline-for-scrub





  # test-bak-delta
  - !Partition
    name: test-bak-delta

    content:
      - !DMCrypt
        name: test-bak-delta
        key-file: /dev/disk/by-partlabel/eva-key

        content: 
          # zfs blockdev inside the partition
          - !ZFSBlockdev
            # name for the zfs pool
            pool: test-bak-delta
          
            # the name of the zfs blockdev
            dev: test-bak-delta
          
            # or just offline
            on_scrubbed: offline-parent

            scrub-interval: 3 weeks







  # once a zpool is being exported, we must generate a "virtual event", because now all backing blockdevs are considered to be offline (so their parent's on_child_offline method must be called)
  - !ZPool
    name: test-bak-delta

    # zfs: test-bak-delta

    on_offline_children: offline

    content:
      
      - !ZFSVolume
        name: sysfs
        on_offline_children: snapshot
        content:
          # it is important that all physical volumes are configured
          - !ZFSBlockdev
            # pvdisplay
            name: bak-delta
            pool: test-sysfs
      
      - !ZFSVolume
        name: big
        on_offline_children: snapshot
        content:
          # it is important that all physical volumes are configured
          - !ZFSBlockdev
            # pvdisplay
            name: bak-delta
            pool: test-big






