[tool.poetry]
name = "zmirror"
version = "0.1.2"
description = ""
authors = ["devvythelopper"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

natsort = ">=8.4.0"
pyyaml = ">=6.0.2"
dateparser = ">=1.2.0"
kpyutils = "^0.1.2"

[tool.poetry.dev-dependencies]
kpyutils = { path = "../kpyutils", develop = true }
debugpy = ">=1.8.14"
pytest = ">=8.3.5"
cysystemd = ">= 0.0.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
