--- !ZMirror
content:
    - !Partition
        name: partition-a
        description: this is partition a
        content:
          - !ZFSBackingDevice
              pool: zpool-a
              dev: partition-a
              description: this is zpool a
          - !ZFSBackingDevice
              pool: zpool-a
              dev: partition-b
              description: this is zpool a
    - !ZPool 
        name: zpool-a

